### ISSUE TITLE
Update deprecated build-push-action@v1 to v2

### ISSUE THREAD

**Issue by rspurgeon** [confluentinc/kafka-devops#21]
Check warning on line 1 in .github

@github-actions github-actions / Release orders-service Image

.github#L1

Input 'repository' has been deprecated with message: v2 beta is now available through docker/build-push-action@v2

https://github.com/docker/github-actions

**Comment by NathBabs** [comment]
Any fix for this yet ?

**Comment by rspurgeon** [comment]
@NathBabs I should be able to address this next week (Dec 21-24).  Thanks for participating in the project

**Comment by rspurgeon** [comment]
@NathBabs updated repo to the v2 GH Action for Docker

**Comment by NathBabs** [comment]
@rspurgeon Thanks, bless

**Comment by TakeoffN** [comment]
Still have a problem with this, please take a look
https://github.com/TakeoffN/github-actions-for-packages/pull/3
